workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
